### ISSUE TITLE
Change Notifications

### ISSUE THREAD

**Issue by wladox09** [YevhenKap/couchdb_dart#16]
hello there is support to get the changes from the database?.

https://guide.couchdb.org/draft/notifications.html

**Comment by YevhenKap** [comment]
Hello. You can use [`changesIn`](https://github.com/YevhenKap/couchdb_dart/blob/6a18ebba40ea7bd87a1e126ffb99a6ec4e7dafd5/lib/src/databases.dart#L352) or [`postChangesIn`](https://github.com/YevhenKap/couchdb_dart/blob/6a18ebba40ea7bd87a1e126ffb99a6ec4e7dafd5/lib/src/databases.dart#L410) of `Databases` class.

**Comment by wladox09** [comment]
ok thank you very much
