### ISSUE TITLE
RealTime listener.

### ISSUE THREAD

**Issue by uwejan** [YevhenKap/couchdb_dart#6]
Hi, i am completely new here,my use case will require realtime API for flutter and the web, some refers me to aqueduct, some mix the first with websockts/ mqtt, been googling, and i saw that couchdb has a listenr notifications for realtime API, i have checked the examples directory found nothing about that, if couchdb is what i should use, can you example me realtime API ,please.

**Comment by YevhenKap** [comment]
@uwejan hello. Do you want to get the latest changes in db across Flutter and Web platform? If it so you maybe want use `changesIn()` method of `DatabaseModel` class with value of `feed` parameter set to `continuous`.
About this you may read [here](http://guide.couchdb.org/draft/notifications.html) and [here](http://docs.couchdb.org/en/stable/api/database/changes.html#continuous).
Hope this help you)

P.S.: I realize that `changesIn()` method with value of `feed` parameter equal to `continuous` must return Stream for ability to listen all event from database. This functional doesn't implemented yet(
