### ISSUE TITLE
flutter_test from sdk is incompatible with couchdb >=0.1.4+1

### ISSUE THREAD

**Issue by GermanCV** [YevhenKap/couchdb_dart#7]
log => Because every version of flutter_test from sdk depends on meta 1.1.6 and couchdb >=0.1.4+1 depends on meta ^1.1.7, flutter_test from sdk is incompatible with couchdb >=0.1.4+1.
So, because couchdb_flutter depends on both couchdb ^0.4.3 and flutter_test any from sdk, version solving failed.

**Comment by YevhenKap** [comment]
Thank you for your issue! I fixed the version constraint of `meta` dependency. Hope you will enjoy using `couchdb` package)
